services:
  mongodb:
    container_name: mongodb-wichat_en3a
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  userservice:
    container_name: userservice-wichat_en3a
    image: ghcr.io/arquisoft/wichat_en3a/userservice:latest
    profiles: ["dev", "prod"]
    build: ./userservice
    depends_on:
      - mongodb
    ports:
      - "8100:8100"
    networks:
      - mynetwork
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/users

  webapp:
    container_name: webapp-wichat_en3a
    image: ghcr.io/arquisoft/wichat_en3a/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
        - mongodb
        - userservice
    environment:
        - USERSERVICE_URL=http://userservice:8100
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_en3a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
      
  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_en3a
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
