openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
  description: API documentation for the Auth Service.
servers:
  - url: http://localhost:8002
    description: Local server for development.
paths:
  /auth/login:
    post:
      summary: Authenticate a user and return a JWT token.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "testuser"
                password:
                  type: string
                  example: "aoeushjfiejsdniofehajdsiovjasiomoim"
      responses:
        '200':
          description: Successful authentication.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Bad request. Some required fields are missing or invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing required field(s): username, password"
        '401':
          description: Unauthorized. Invalid user or password.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid user or password"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"

  /auth/register:
    post:
      summary: Register a new user
      description: Register a new user and return the JWT token for authentication.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "newuser"
                password:
                  type: string
                  example: "newpassword"
                role:
                  type: string
                  enum:
                    - ADMIN
                    - USER
                  example: "USER"
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "JWT_TOKEN"              
        '400':
          description: Missing required field(s) or validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing required field(s): username, password"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"

  /auth/setup2fa:
    post:
      summary: Set up 2FA for the user.
      description: Generates a QR code URL for setting up 2FA.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user"
      responses:
        '200':
          description: Successful 2FA setup.
          content:
            application/json:
              schema:
                type: object
                properties:
                  imageUrl:
                    type: string
                    example: "data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA..."
        '400':
          description: Bad request. Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Username is required"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error generating QR code"

  /auth/verify2fa:
    post:
      summary: Verify the 2FA token provided by the user.
      description: Verifies the token submitted by the user for 2FA.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "123456"
                secret:
                  type: string
                  example: "JBSWY3DPEHPK3PXP"
      responses:
        '200':
          description: Successful 2FA verification.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "2FA Verified"
        '400':
          description: Missing or invalid parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Token and Secret are required"
        '401':
          description: Unauthorized. Invalid 2FA token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid 2FA Token"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error verifying 2FA token"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
