name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'
      - run: mvn clean test --batch-mode
        working-directory: userservice
      - run: mvn clean test --batch-mode
        working-directory: hintservice
      - run: mvn clean test --batch-mode
        working-directory: wikidataservice
      - run: mvn clean test --batch-mode
        working-directory: webapp
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
