name: Build
on:
  push:
    branches:
      - master
      - development
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Create .env file for hintservice
        run: |
          echo "HINTSERVICE_API_KEY=${{ secrets.LLM_API_KEY }}" > .env

      # Run Tests for All Services
      - name: Run Tests and Generate Coverage
        run: |
          mvn clean verify --batch-mode -pl userservice
          mvn clean verify --batch-mode -pl hintservice
          mvn clean verify --batch-mode -pl wikidataservice
          mvn clean verify --batch-mode -pl webapp
        env:
          llm.apikey: ${{ secrets.HINTSERVICE_API_KEY }}

      # Run SonarCloud from the Root Directory
      - name: Analyze with SonarCloud
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=arquisoft -Dsonar.projectKey=Arquisoft_wichat_en3a
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
